services:
  db:
    image: "postgres:latest"
    ports:
    - "5432:5432"
    environment: 
    - POSTGRES_PASSWORD=admin
    - POSTGRES_USER=admin
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    
    
